# This file tells Google Cloud Build how to deploy the application.
# It can be attached to a variety of triggers, the default being whenever
# someone merges changes to the `master` branch.
timeout: '3600s'
steps:
# Pull the latest Docker image, so the build is faster.
- id: 'image.pull'
  waitFor: ['-']
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0'
  ]
# Build the Docker image
- id: 'image.build'
  waitFor: ['image.pull']
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '--tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.',
  ]
# Push the Docker image to be deployed
- id: 'image.push'
  waitFor: ['image.build']
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  ]
# Generate the Kubernetes configuration for the norms demo
- id: 'config.norms'
  waitFor: ['-']
  name: 'gcr.io/ai2-reviz/jsonnet'
  args: [
    'eval',
    '--yaml-stream',
    '--output-file', './norms.webapp.yaml',
    '--tla-str', 'app=norms',
    '--tla-str', 'env=$_ENV',
    '--tla-str', 'image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--tla-str', 'sha=$COMMIT_SHA',
    '--tla-str', 'cause=Automated Skiff Deploy SHA:$COMMIT_SHA BUILD:$BUILD_ID',
    '--tla-str', 'branch=$BRANCH_NAME',
    '--tla-str', 'repo=$REPO_NAME',
    '--tla-str', 'buildId=$BUILD_ID',
    './webapp.jsonnet'
  ]
  dir: '.skiff'
# Generate the Kubernetes configuration for the scoracle demo
- id: 'config.scoracle'
  waitFor: ['-']
  name: 'gcr.io/ai2-reviz/jsonnet'
  args: [
    'eval',
    '--yaml-stream',
    '--output-file', './scoracle.webapp.yaml',
    '--tla-str', 'app=scoracle',
    '--tla-str', 'env=$_ENV',
    '--tla-str', 'image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--tla-str', 'sha=$COMMIT_SHA',
    '--tla-str', 'cause=Automated Skiff Deploy SHA:$COMMIT_SHA BUILD:$BUILD_ID',
    '--tla-str', 'branch=$BRANCH_NAME',
    '--tla-str', 'repo=$REPO_NAME',
    '--tla-str', 'buildId=$BUILD_ID',
    './webapp.jsonnet'
  ]
  dir: '.skiff'
# Deploy the norms demo to Kubernetes
- id: 'deploy.norms'
  waitFor: ['image.push', 'config.norms']
  name: 'gcr.io/ai2-reviz/rudder'
  args: [
    'deploy',
    '-f',
    'norms.webapp.yaml'
  ]
  dir: '.skiff'
# Deploy the scoracle demo to Kubernetes
- id: 'deploy.scoracle'
  waitFor: ['image.push', 'config.scoracle']
  name: 'gcr.io/ai2-reviz/rudder'
  args: [
    'deploy',
    '-f',
    'scoracle.webapp.yaml'
  ]
  dir: '.skiff'
substitutions:
  _ENV: staging
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
]
artifacts:
  objects:
    location: 'gs://skiff-archive/$REPO_NAME/$_ENV/$BUILD_ID/$COMMIT_SHA'
    paths: ['.skiff/norms.webapp.yaml', '.skiff/scoracle.webapp.yaml']
